version: "3.3"

services:
  mysql:
    image: mysql:5.6
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: pesho
      MYSQL_PASSWORD: peshev
      MYSQL_ROOT_PASSWORD: gosho
      MYSQL_DATABASE: feedback
  nginx:
      image: nginx:1.15.3-alpine
      restart: on-failure
      depends_on:
        - php
      volumes:
        - './public/:/usr/src/app'
        - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
      ports:
        - '80:80'
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    env_file:
      - .env
    user: 1000:1000
